version: '3.1'

services:
  api:
    image: 'josiahgoodson/cloudbreak-cuisine-backend'
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 4000:4000
    links:
      - db
      - whoville
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_pass123!
    volumes:
      - ./backend/assets/db_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  whoville:
    image: 'chaffelson/whoville:latest'
    volumes:
      - ${PROFILE}:/profile.yml:ro
    ports:
      - 5000:5000