version: '3.1'

services:
  ui:
      image: 'pvidal/bmq-frontend:latest'
      volumes:
        - ../frontend:/usr/src/app
      ports:
        - 3001:3001
      links:
        - api
        - whoville
  api:
    image: 'pvidal/bmq-backend:latest'
    volumes:
      - ../backend:/usr/src/app
    ports:
      - 4001:4001
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_pass123!
    volumes:
      - ../backend/assets/db_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080